name: PR File Change

on:
  pull_request:
    branches: [master]

jobs:
  pr-file-change:
    name: pr-file-change
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: PR Diff
        run: yarn run pr-diff

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          readarray -t removed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.removed }}')"
          for removed_file in ${removed_files[@]}; do
            yarn run throw-error
          done